---
AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

# Rails convention uses the parameter f for fields in view helpers
Naming/MethodParameterName:
  Exclude: 'app/helpers/**/*.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false

